services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
    image: bot:latest
    container_name: bot
    restart: unless-stopped
    user: 10001:10001
    env_file:
      - .env
    volumes:
      - ./data:/opt/app/data
